version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosec
    - ineffassign
    - depguard
    - gomoddirectives
  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          allow:
            - $gostd
            - golang.org/x/
            - github.com/dustin/go-humanize
            - github.com/google/
            - github.com/kballard/go-shellquote
            - github.com/lithammer/fuzzysearch
            - github.com/mattn/
            - github.com/pmezard/go-difflib
            - github.com/remyoudompheng/bigfft
            - github.com/yuin/goldmark
            - lukechampine.com/uint128
            - modernc.org/
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (io.Closer).Close
        - (io.ReadCloser).Close
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Print
        - fmt.Println
        - fmt.Printf
    gosec:
      excludes:
        - G304
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
      - text: "Error return value of .*.Close"
        linters:
          - errcheck
